# Generated by Django 3.0.8 on 2021-04-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopper',
            name='idSlack',
            field=models.CharField(default='', max_length=20),
        ),
    ]
