# Generated by Django 3.0.8 on 2021-04-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_shopper_idslack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopper',
            name='idSlack',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
